### ISSUE TITLE
Bookdown

### ISSUE THREAD

**Issue by rosstox26** [nayib-asis/woodsmen_MBAN501#2]
As a priority task, you would want to install the Bookdown package and create the demo bookdown "book" - you will then be able to edit the demo book to create your content.

**Comment by rosstox26** [comment]
Any updates folks?

**Comment by nayib-asis** [comment]
Hi Professor, we’ll get to it right now and comment accordingly if we bump into any issues

**Comment by rosstox26** [comment]
Thanks Nayib. You may want to check this as a reference: https://github.com/Ameybhile/MBAn_Career_Handbook

**Comment by rosstox26** [comment]
or this: https://github.com/rorymeyer/KRYRK

**Comment by rosstox26** [comment]
Your output directory needs to be called "docs". See the last line of this file for how to make this happen: https://github.com/rorymeyer/KRYRK/blob/main/_bookdown.yml

Then go to settings -> pages and choose Main / docs to enagle GitHub pages.
